### ISSUE TITLE
Need to check relayer repository

### ISSUE THREAD

**Issue by zemyblue** [Finschia/tutorials#8]
We need to check which relayer repo is appropriate with our finschia node. 
* in order to use relayer
* in order to add url in document. 
  * https://github.com/Finschia/hackathon/blob/ac7ed5a3df86085c71b993d945900d4822beb606/dashboard/README.md?plain=1#L3

**Comment by tkxkd0159** [comment]
Confirmed : [v2.3.1](https://github.com/cosmos/relayer/releases/tag/v2.3.1)
